# Generated by Django 4.2.6 on 2023-11-03 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_userprofile_avatar_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
