# Generated by Django 4.2.6 on 2023-11-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.category'),
        ),
    ]
